name: Frontend CI

on:
  pull_request:
    branches: [ development, main ]
    paths:
      - "frontend/**"
  push:
    branches: [ main ]
    paths:
      - "frontend/**"

jobs:
  frontend-ci:
    uses: ./.github/workflows/ci.yml
    with:
      service: frontend
      language: node
